package handlers

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/user/antimoney/internal/auth"
)

type ImportExportHandler struct {
	pool *pgxpool.Pool
}

func NewImportExportHandler(pool *pgxpool.Pool) *ImportExportHandler {
	return &ImportExportHandler{pool: pool}
}

func (h *ImportExportHandler) Routes() chi.Router {
	r := chi.NewRouter()
	r.Post("/import", h.handleImport)
	r.Get("/export", h.handleExport)
	return r
}

func (h *ImportExportHandler) handleImport(w http.ResponseWriter, r *http.Request) {
	// Parse the multipart form
	err := r.ParseMultipartForm(10 << 20) // 10 MB limit
	if err != nil {
		writeError(w, http.StatusBadRequest, "failed to parse multipart form")
		return
	}

	file, _, err := r.FormFile("file")
	if err != nil {
		writeError(w, http.StatusBadRequest, "file is required")
		return
	}
	defer file.Close()

	sqlBytes, err := io.ReadAll(file)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to read file")
		return
	}

	sqlStr := string(sqlBytes)

	// Ensure not empty
	if len(strings.TrimSpace(sqlStr)) == 0 {
		writeError(w, http.StatusBadRequest, "empty sql file")
		return
	}

	bookGUID := auth.BookGUIDFromCtx(r.Context())
	if bookGUID == "" {
		writeError(w, http.StatusUnauthorized, "missing book guid")
		return
	}

	// We need to inject the current user's book GUID into the SQL script.
	// The script generated by export or convert_csv.js generally starts with:
	// DECLARE
	//     v_book_guid uuid;
	//     v_cad_guid uuid;
	// BEGIN
	//     SELECT guid INTO v_book_guid FROM books LIMIT 1;
	// We will replace this finding of v_book_guid with a hardcoded assignment:
	//     v_book_guid uuid := '...';

	// We can simply replace `v_book_guid uuid;` or the SELECT statement, but since we know
	// the export generates `v_book_guid uuid := '...';`, and convert_csv.js generates a SELECT,
	// it's safer to just inject a SET command or rely on the script being parameterized.
	// Actually, the easiest way to make this secure and multi-tenant is to force
	// v_book_guid to always be the current user's book by injecting it right after BEGIN.

	// Example script replacement to ensure multi-tenancy:
	// If the script contains `SELECT guid INTO v_book_guid FROM books LIMIT 1;`, we replace it.
	sqlStr = strings.Replace(sqlStr, "SELECT guid INTO v_book_guid FROM books LIMIT 1;", "v_book_guid := '"+bookGUID+"';", 1)

	// If it contains the export format: `v_book_guid uuid := '...';` we replace that too.
	// We can use a regex, or simple string replacement if we know the patterns.
	// Let's just prepend a block that overwrites v_book_guid right after BEGIN.
	sqlStr = strings.Replace(sqlStr, "BEGIN", "BEGIN\n    v_book_guid := '"+bookGUID+"';\n", 1)

	// Execute it in a transaction
	tx, err := h.pool.Begin(r.Context())
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to start transaction")
		return
	}
	defer tx.Rollback(r.Context())

	_, err = tx.Exec(r.Context(), sqlStr)
	if err != nil {
		writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to execute sql: %v", err))
		return
	}

	if err := tx.Commit(r.Context()); err != nil {
		writeError(w, http.StatusInternalServerError, "failed to commit transaction")
		return
	}

	writeJSON(w, http.StatusOK, map[string]string{"message": "import successful"})
}

func (h *ImportExportHandler) handleExport(w http.ResponseWriter, r *http.Request) {
	bookGUID := auth.BookGUIDFromCtx(r.Context())
	if bookGUID == "" {
		writeError(w, http.StatusUnauthorized, "missing book guid")
		return
	}

	// We generate the export logic
	var sb strings.Builder

	sb.WriteString("DO $$\n")
	sb.WriteString("DECLARE\n")
	sb.WriteString("    v_book_guid uuid := '" + bookGUID + "';\n")
	sb.WriteString("BEGIN\n")
	sb.WriteString("    -- Delete existing to replace (optional for import, but standard)\n")
	sb.WriteString("    DELETE FROM splits WHERE tx_guid IN (SELECT guid FROM transactions WHERE book_guid = v_book_guid);\n")
	sb.WriteString("    DELETE FROM transactions WHERE book_guid = v_book_guid;\n")
	sb.WriteString("    DELETE FROM accounts WHERE book_guid = v_book_guid;\n")

	// Export accounts
	rows, err := h.pool.Query(r.Context(),
		`SELECT guid, name, account_type, commodity_guid, commodity_scu, parent_guid, placeholder, description 
		 FROM accounts WHERE book_guid = $1
		 ORDER BY parent_guid ASC NULLS FIRST`, bookGUID)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to export accounts")
		return
	}
	defer rows.Close()

	for rows.Next() {
		var guid, name, accType, commGuid, desc string
		var commScu int
		var parentGuid *string
		var placeholder bool

		if err := rows.Scan(&guid, &name, &accType, &commGuid, &commScu, &parentGuid, &placeholder, &desc); err != nil {
			writeError(w, http.StatusInternalServerError, "error reading accounts")
			return
		}

		name = strings.ReplaceAll(name, "'", "''")
		desc = strings.ReplaceAll(desc, "'", "''")

		pg := "NULL"
		if parentGuid != nil {
			pg = "'" + *parentGuid + "'::uuid"
		}

		ph := "false"
		if placeholder {
			ph = "true"
		}

		sb.WriteString("    INSERT INTO accounts (guid, name, account_type, commodity_guid, commodity_scu, parent_guid, book_guid, placeholder, description)\n")
		sb.WriteString(fmt.Sprintf("    VALUES ('%s', '%s', '%s', '%s', %d, %s, v_book_guid, %s, '%s');\n", guid, name, accType, commGuid, commScu, pg, ph, desc))
	}
	rows.Close()

	// Export transactions
	txRows, err := h.pool.Query(r.Context(),
		`SELECT guid, currency_guid, post_date, enter_date, description 
		 FROM transactions WHERE book_guid = $1`, bookGUID)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to export txs")
		return
	}
	defer txRows.Close()

	for txRows.Next() {
		var guid, currGuid, desc string
		var postDate, enterDate string // Keep as string for formatting
		if err := txRows.Scan(&guid, &currGuid, &postDate, &enterDate, &desc); err != nil {
			continue
		}
		desc = strings.ReplaceAll(desc, "'", "''")
		sb.WriteString("    INSERT INTO transactions (guid, currency_guid, book_guid, post_date, enter_date, description)\n")
		sb.WriteString(fmt.Sprintf("    VALUES ('%s', '%s', v_book_guid, '%s', '%s', '%s');\n", guid, currGuid, postDate, enterDate, desc))

		// Get splits for this tx
		spRows, err := h.pool.Query(context.Background(),
			`SELECT guid, account_guid, memo, value_num, value_denom, quantity_num, quantity_denom, reconcile_state 
			 FROM splits WHERE tx_guid = $1`, guid)
		if err == nil {
			for spRows.Next() {
				var sg, ag, memo, recState string
				var vn, vd, qn, qd int64
				if err := spRows.Scan(&sg, &ag, &memo, &vn, &vd, &qn, &qd, &recState); err == nil {
					memo = strings.ReplaceAll(memo, "'", "''")
					sb.WriteString("    INSERT INTO splits (guid, tx_guid, account_guid, memo, value_num, value_denom, quantity_num, quantity_denom, reconcile_state)\n")
					sb.WriteString(fmt.Sprintf("    VALUES ('%s', '%s', '%s', '%s', %d, %d, %d, %d, '%s');\n", sg, guid, ag, memo, vn, vd, qn, qd, recState))
				}
			}
			spRows.Close()
		}
	}
	txRows.Close()

	sb.WriteString("END $$;\n")

	w.Header().Set("Content-Type", "application/sql")
	w.Header().Set("Content-Disposition", "attachment; filename=\"export.sql\"")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(sb.String()))
}
